name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check_lint:
    defaults:
      run:
        working-directory: "stackql_deploy"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install ruff

      - name: Lint check with ruff
        run: ruff check .
